<?php

/**
 * @file
 * An a example how to create view mode using program.
 */

/**
 * Implements hook_entity_info_alter(). 
 */

function custom_view_mode_entity_info_alter(&$entity_info) {
	$entity_info['node']['view modes']['my_view_mode'] = array(
	   'label' => t('My View Mode'),
	   'custom settings' => TRUE,
	);
}

/**
 * Implements hook_preprocess_node().
 */
function custom_view_mode_preprocess_node(&$variables) {
  if($variables['view_mode'] == 'my_view_mode') {
    $variables['theme_hook_suggestions'][] = 'node__' . $variables['type'] . '__my_view_mode_custom';
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function custom_view_mode_entity_view_mode_alter(&$view_mode, $context) {
  // For nodes, change the view mode when it is teaser.
  if ($context['entity_type'] == 'node' && $view_mode == 'teaser') {
     //$view_mode = 'my_view_mode';
  }
}